repositoryUrl: https://github.com/Tom-Dynamsoftblob/master

docHomePage: /
dynamsoft_logo: /assets/img-icon/dynamsoft-logo.png
dwt_logo: /assets/img-icon/dwt-logo.png

assets: /assets/
_includes: /_includes/
_layouts: /_layouts/
about: /about/
getstarted: /getstarted/
indepth: /indepth/
info: /info/
theme: jekyll-theme-cayman